version: '2'

services:
   db:
    image: mysql:5.7
    volumes:
      - /opt/${APP_URI}/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress

   wordpress:
      image: wordpress:latest
      volumes:
      - /opt/${APP_URI}/wordpress/:/var/www/html/
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.backend=wordpress"
        - "traefik.frontend.rule=Host:${APP_URI}"
        - "traefik.port=80"
        - "traefik.docker.network=web"
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
      networks:
        - web
        - wordpress

networks:
  web:
    external:
      name: web