version: '2'

services:

  peertube:
    image: chocobozzz/peertube:production-stretch
    environment:
      - PEERTUBE_DB_USERNAME=root
      - PEERTUBE_DB_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - PEERTUBE_WEBSERVER_HOSTNAME=${APP_URI}
      - PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16"]
      - PEERTUBE_SMTP_HOSTNAME=postfix
      - PEERTUBE_SMTP_PORT=25
      - PEERTUBE_SMTP_FROM=noreply@rhos.club
      - PEERTUBE_SMTP_TLS=false
      - PEERTUBE_SMTP_DISABLE_STARTTLS=false
      - PEERTUBE_ADMIN_EMAIL=admin@rhos.club
    labels:
      - "traefik.enable=true"
      - "traefik.backend=peertube"
      - "traefik.frontend.rule=Host:${APP_URI}"
      - "traefik.port=9000"
      - "traefik.docker.network=web"
    volumes:
      - /opt/${APP_URI}/data:/data
      - /opt/${APP_URI}/config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    networks:
      - web
      - peertube
    restart: "always"

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: peertube
    volumes:
      - /opt/${APP_URI}/postgres:/var/lib/postgresql/data
    restart: "always"
    networks:
      - peertube

  redis:
    image: redis:4-alpine
    volumes:
      - /opt/${APP_URI}/redis:/data
    restart: "always"
    networks:
      - peertube

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=mail.${APP_URI}
    restart: "always"
    networks:
      - peertube

networks:
  web:
    external:
      name: web