version: '2'

services:
   db:
    image: mysql:5.7
    volumes:
      - /opt/${APP_URI}/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    networks:
      - ghost

   ghost:
      image: ghost:2.25.4-alpine
      # volumes:
      # - /opt/${APP_URI}/ghost/:/var/lib/ghost/content/
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.backend=ghost"
        - "traefik.frontend.rule=Host:${APP_URI}"
        - "traefik.port=2368"
        - "traefik.docker.network=web"
      environment:
        url: https://${url}
        database__client: mysql
        database__connection__host: db
        database__connection__user: root
        database__connection__password: ${MYSQL_DATABASE_PASSWORD}
        database__connection__database: ghost
      networks:
        - web
        - ghost

networks:
  web:
    external:
      name: web