version: '2'
services:
   db:
    image: mysql:5
    volumes:
      - /opt/${APP_URI}/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
    networks:
      - ghost
   ghost:
      image: ghost:alpine
      # volumes:
      # - /opt/${APP_URI}/ghost/:/var/lib/ghost/content/
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.backend=ghost"
        - "traefik.frontend.rule=Host:${APP_URI}"
        - "traefik.port=2368"
        - "traefik.docker.network=web"
      environment:
        url: "https://${APP_URI}"
        database__client: mysql
        database__connection__host: db
        database__connection__user: ghost
        database__connection__password: ${MYSQL_DATABASE_PASSWORD}
        database__connection__database: ghost
      networks:
        - web
        - ghost
networks:
  web:
    external:
      name: web
