version: '2'

services:
   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    volumes:
      - /opt/${APP_URI}/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=phpmyadmin"
      - "traefik.frontend.rule=Host:${APP_URI}"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    environment:
      PMA_ABSOLUTE_URI: "https://${APP_URI}"
    networks:
      - web

networks:
  web:
    external:
      name: web